version: '3.8'
services:
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - app-network

  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - discovery-service
    networks:
      - app-network

  movie-service:
    build:
      context: ./movie-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - TMDB_API_KEY=your_api_key
      - TMDB_API_BASE_URL=https://api.themoviedb.org/3
    depends_on:
      - discovery-service
      - config-service
    networks:
      - app-network

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - discovery-service
      - movie-service
      - config-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge